# Generated by Django 5.0.2 on 2024-02-08 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='isStudent',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
