# Generated by Django 5.0.2 on 2024-02-14 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0004_course_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='experience',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
