# Generated by Django 5.0.2 on 2024-02-17 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0005_mentor_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='skills',
            field=models.TextField(default='C++'),
            preserve_default=False,
        ),
    ]
