# Generated by Django 5.0.2 on 2024-02-17 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0006_course_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='skills',
        ),
    ]
