# Generated by Django 5.0.2 on 2024-02-17 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0007_remove_course_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='skills',
            field=models.TextField(default='C++'),
            preserve_default=False,
        ),
    ]
